name = input("Enter your name: ")
print("Length of string:", len(name))
print("Lower case:", name.lower())
print("Upper case:", name.upper())
print("Title case:", name.title())
print("Capitalize:", name.capitalize())
print("Swap case:", name.swapcase())
print("Strip:", name.strip())
print("lstrip:", name.lstrip())
print("rstrip:", name.rstrip())
print("center(20):", name.center(20))
print("ljust(20):", name.ljust(20))
print("rjust(20):", name.rjust(20))
print("zfill(20):", name.zfill(20))
print("Count of 'a':", name.count("a"))
print("Find 'a':", name.find("a"))
print("Index of 'a':", name.index("a"))
print("Replace 'a' with 'b':", name.replace("a", "b"))
print("Split by ' ':", name.split(" "))
print("Join with ['a','b','c']:", name.join(["a", "b", "c"]))
print("Is digit:", name.isdigit())
print("Is alpha:", name.isalpha())
